server:
  port: 8883
  address: localhost
  servlet:
    context-path: /inventory-service
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-dev:3306/tcc_stock?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  application:
    name: inventory-service
mybatis:
  type-aliases-package: com.li.tcc.demo.springcloud.inventory.entity
  config-location: classpath:mybatis/mybatis-config.xml
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
inventory-service:
  ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    root: info
    com.li.tcc: debug
  path: /logs/li-tcc-demo-springcloud-inventory