server:
  port: 8884
  address: localhost
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-dev:3306/tcc_order?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  application:
    name: order-service
mybatis:
  type-aliases-package: com.li.tcc.demo.springcloud.order.entity
  config-location: classpath:mybatis/mybatis-config.xml
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    root: info
    com.li.tcc: debug
  path: /logs/li-tcc-demo-springcloud-order